import {
  BadgeIndianRupee,
  CalendarCheck,
  CheckCircle2,
  Clock3,
  Mail,
  MapPin,
  MessageSquareText,
  Phone,
  Send,
  ShieldCheck,
  Star,
  UsersRound,
  X
} from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { apiClient, formatCurrency, getErrorMessage } from "../api/client.js";
import { useAuth } from "../context/AuthContext.jsx";

const initialInquiry = {
  name: "",
  phone: "",
  email: "",
  eventType: "Wedding",
  eventDate: "",
  budget: "",
  guestCount: "",
  location: "",
  message: "",
  selectedPackage: null
};

const fallbackReviews = [
  {
    _id: "fallback-1",
    name: "Aarav Mehta",
    rating: 5,
    comment: "The team handled our wedding with calm precision. Every guest movement and decor detail felt cared for."
  },
  {
    _id: "fallback-2",
    name: "Nisha Rao",
    rating: 5,
    comment: "Our annual day looked premium and ran exactly on schedule. The dashboard updates were very useful."
  }
];

const Home = () => {
  const { isAuthenticated, user } = useAuth();
  const navigate = useNavigate();
  const [services, setServices] = useState([]);
  const [packages, setPackages] = useState([]);
  const [reviews, setReviews] = useState(fallbackReviews);
  const [inquiry, setInquiry] = useState(initialInquiry);
  const [inquiryModalOpen, setInquiryModalOpen] = useState(false);
  const [status, setStatus] = useState({ type: "", message: "" });
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadHome = async () => {
      try {
        const [servicesResult, packagesResult, reviewsResult] = await Promise.allSettled([
          apiClient.get("/catalog/services"),
          apiClient.get("/catalog/packages"),
          apiClient.get("/reviews")
        ]);

        if (servicesResult.status === "fulfilled") {
          setServices(servicesResult.value.data);
        }

        if (packagesResult.status === "fulfilled") {
          setPackages(packagesResult.value.data);
        }

        if (reviewsResult.status === "fulfilled" && reviewsResult.value.data.length) {
          setReviews(reviewsResult.value.data);
        }
      } catch (_error) {
        // The public page remains usable with fallback content if the API is not configured yet.
      }
    };

    loadHome();
  }, []);

  const onChange = (event) => {
    setInquiry((current) => ({
      ...current,
      [event.target.name]: event.target.value
    }));
  };

  const openInquiryModal = (updates = {}) => {
    if (!isAuthenticated) {
      navigate("/login", {
        state: {
          from: "/",
          notice: "Please login before sending an event inquiry."
        }
      });
      return;
    }

    setInquiry((current) => ({
      ...current,
      name: current.name || user?.name || "",
      phone: current.phone || user?.phone || "",
      email: current.email || user?.email || "",
      ...updates
    }));
    setStatus({ type: "", message: "" });
    setInquiryModalOpen(true);
  };

  const closeInquiryModal = () => {
    if (!loading) {
      setInquiryModalOpen(false);
    }
  };

  const submitInquiry = async (event) => {
    event.preventDefault();
    setLoading(true);
    setStatus({ type: "", message: "" });

    try {
      await apiClient.post("/events/public-inquiry", {
        ...inquiry,
        guestCount: Number(inquiry.guestCount || 0)
      });
      setInquiry(initialInquiry);
      setStatus({ type: "success", message: "Inquiry submitted. Our team will contact you soon." });
      setInquiryModalOpen(false);
    } catch (error) {
      setStatus({ type: "error", message: getErrorMessage(error) });
    } finally {
      setLoading(false);
    }
  };

  const choosePlan = (item) => {
    const autoGeneratedMessage =
      !inquiry.message ||
      inquiry.message.startsWith("I want to plan a") ||
      inquiry.message.startsWith("I am interested in the");

    openInquiryModal({
      budget: item.price ? String(item.price) : inquiry.budget,
      selectedPackage: {
        packageId: item._id,
        name: item.name,
        price: item.price,
        description: item.description
      },
      message:
        autoGeneratedMessage
          ? `I am interested in the ${item.name} package. Please share the final proposal for my event.`
          : inquiry.message ||
        `I am interested in the ${item.name} package. Please share the final proposal for my event.`
    });
  };

  const requestService = (service) => {
    const eventType =
      service.category === "Social" ? "Birthday" : service.category === "Live" ? "Concert" : service.category;

    openInquiryModal({
      eventType: eventType || service.title,
      budget: service.basePrice ? String(service.basePrice) : inquiry.budget,
      message: `I want to plan a ${service.title} event. Please contact me with options and pricing.`
    });
  };

  const visibleServices =
    services.length > 0
      ? services
      : [
          {
            _id: "wedding",
            title: "Wedding Planning",
            category: "Wedding",
            basePrice: 150000,
            description: "Full wedding planning, decor, guest flow, hospitality, and day-of coordination.",
            imageUrl:
              "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80"
          },
          {
            _id: "corporate",
            title: "Corporate Events",
            category: "Corporate",
            basePrice: 90000,
            description: "Conferences, launches, annual days, stage production, and registration operations.",
            imageUrl:
              "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80"
          },
          {
            _id: "concert",
            title: "Live Events",
            category: "Live",
            basePrice: 250000,
            description: "Concerts, festivals, artist coordination, lighting, sound, and crowd movement.",
            imageUrl:
              "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&w=1200&q=80"
          }
        ];

  const visiblePackages =
    packages.length > 0
      ? packages
      : [
          {
            _id: "essential",
            name: "Essential",
            price: 49999,
            description: "Planning support for small gatherings.",
            features: ["Event consultation", "Planning checklist", "Basic decor plan", "Day-of coordination"]
          },
          {
            _id: "signature",
            name: "Signature",
            price: 149999,
            description: "Full planning package for premium events.",
            features: ["Theme design", "Service planning", "Budget tracking", "Event manager"]
          },
          {
            _id: "luxury",
            name: "Luxury",
            price: 399999,
            description: "High-touch planning with production and hospitality.",
            features: ["Custom concept", "Dedicated team", "VIP hospitality", "Post-event reporting"]
          }
        ];

  return (
    <main>
      <section className="hero">
        <div className="hero-overlay" />
        <div className="hero-content">
          <span className="eyebrow">
            <CalendarCheck size={18} />
            End-to-end event planning platform
          </span>
          <h1>Festive Events</h1>
          <p>
            Plan weddings, corporate gatherings, private celebrations, and live experiences with one team handling
            proposals, invoices, payments, planning updates, and event-day execution.
          </p>
          <div className="hero-actions">
            <button className="button primary" type="button" onClick={() => openInquiryModal()}>
              <Send size={18} />
              {isAuthenticated ? "Get Quote" : "Login to Get Quote"}
            </button>
            <Link to="/login" className="button light">
              <ShieldCheck size={18} />
              Client Login
            </Link>
          </div>
        </div>
        <div className="hero-metrics">
          <span>
            <strong>1</strong>
            Client portal
          </span>
          <span>
            <strong>24/7</strong>
            Lead capture
          </span>
          <span>
            <strong>100%</strong>
            Digital workflow
          </span>
        </div>
      </section>

      <section className="section info-strip">
        <div>
          <Clock3 size={24} />
          <span>Fast lead response</span>
        </div>
        <div>
          <BadgeIndianRupee size={24} />
          <span>Online invoices and payments</span>
        </div>
        <div>
          <UsersRound size={24} />
          <span>Dedicated event team support</span>
        </div>
      </section>

      <section className="section" id="services">
        <div className="section-heading">
          <span className="eyebrow">Services</span>
          <h2>Every event type, managed from inquiry to review</h2>
        </div>
        <div className="service-grid">
          {visibleServices.map((service) => (
            <article className="service-card" key={service._id}>
              <img src={service.imageUrl} alt={service.title} />
              <div>
                <span>{service.category}</span>
                <h3>{service.title}</h3>
                <p>{service.description}</p>
                <strong>Starts at {formatCurrency(service.basePrice)}</strong>
                <button className="button ghost full service-action" type="button" onClick={() => requestService(service)}>
                  <MessageSquareText size={18} />
                  {isAuthenticated ? "Request This Event" : "Login to Request Event"}
                </button>
              </div>
            </article>
          ))}
        </div>
      </section>

      <section className="section muted-band" id="packages">
        <div className="section-heading">
          <span className="eyebrow">Packages</span>
          <h2>Flexible plans for simple and premium events</h2>
        </div>
        <div className="package-grid">
          {visiblePackages.map((item) => (
            <article className="package-card" key={item._id}>
              <h3>{item.name}</h3>
              <strong>{formatCurrency(item.price)}</strong>
              <p>{item.description}</p>
              <ul>
                {item.features.map((feature) => (
                  <li key={feature}>
                    <CheckCircle2 size={16} />
                    {feature}
                  </li>
                ))}
              </ul>
              <button className="button primary full package-action" type="button" onClick={() => choosePlan(item)}>
                <CheckCircle2 size={18} />
                {isAuthenticated ? "Choose Plan" : "Login to Choose Plan"}
              </button>
            </article>
          ))}
        </div>
      </section>

      <section className="section split-section" id="inquiry">
        <div className="inquiry-copy">
          <span className="eyebrow">Start a booking</span>
          <h2>Tell us what you are planning</h2>
          <p>
            Your inquiry becomes a Contact us request. From there, the team can send proposals, create
            invoices, collect payments, and keep your event status updated.
          </p>
          <div className="contact-stack">
            <span>
              <Phone size={18} />
              +91 98765 43210
            </span>
            <span>
              <Mail size={18} />
              hello@festive.local
            </span>
            <span>
              <MapPin size={18} />
              Available for events across India
            </span>
          </div>
        </div>

        <div className="form-panel inquiry-launch-panel">
          <span className="eyebrow">Popup request</span>
          <h3>Send your event details to Contact us</h3>
          <p>
            Select an event type or package above, then complete the popup form with your budget, date, guest count,
            location, and description.
          </p>
          {status.message && <p className={`form-message ${status.type}`}>{status.message}</p>}
          <button className="button primary full" type="button" onClick={() => openInquiryModal()}>
            <MessageSquareText size={18} />
            {isAuthenticated ? "Open Request Popup" : "Login to Send Request"}
          </button>
        </div>
      </section>

      <section className="section" id="reviews">
        <div className="section-heading">
          <span className="eyebrow">Reviews</span>
          <h2>Approved testimonials from completed events</h2>
        </div>
        <div className="review-grid">
          {reviews.slice(0, 3).map((review) => (
            <article className="review-card" key={review._id}>
              <div className="stars">
                {Array.from({ length: review.rating }).map((_, index) => (
                  <Star key={index} size={16} fill="currentColor" />
                ))}
              </div>
              <p>{review.comment}</p>
              <strong>{review.name}</strong>
            </article>
          ))}
        </div>
      </section>

      {inquiryModalOpen && (
        <div className="modal-backdrop" role="presentation" onMouseDown={closeInquiryModal}>
          <section
            className="request-modal"
            role="dialog"
            aria-modal="true"
            aria-labelledby="request-modal-title"
            onMouseDown={(event) => event.stopPropagation()}
          >
            <div className="modal-header">
              <div>
                <span className="eyebrow">Event request</span>
                <h2 id="request-modal-title">Tell us about your event</h2>
              </div>
              <button className="icon-button" type="button" onClick={closeInquiryModal} aria-label="Close request popup">
                <X size={18} />
              </button>
            </div>

            <form className="form-panel flat modal-form" onSubmit={submitInquiry}>
              {inquiry.selectedPackage && (
                <div className="selected-package">
                  <span>Selected plan</span>
                  <strong>
                    {inquiry.selectedPackage.name} - {formatCurrency(inquiry.selectedPackage.price)}
                  </strong>
                  <p>{inquiry.selectedPackage.description}</p>
                </div>
              )}
              <div className="form-grid two">
                <label>
                  Name
                  <input name="name" value={inquiry.name} onChange={onChange} required />
                </label>
                <label>
                  Phone
                  <input name="phone" value={inquiry.phone} onChange={onChange} required />
                </label>
                <label>
                  Email
                  <input type="email" name="email" value={inquiry.email} onChange={onChange} required />
                </label>
                <label>
                  Event type
                  <select name="eventType" value={inquiry.eventType} onChange={onChange}>
                    <option>Wedding</option>
                    <option>Corporate</option>
                    <option>Birthday</option>
                    <option>Concert</option>
                    <option>Product Launch</option>
                    <option>Other</option>
                  </select>
                </label>
                <label>
                  Event date
                  <input type="date" name="eventDate" value={inquiry.eventDate} onChange={onChange} required />
                </label>
                <label>
                  Guest count
                  <input type="number" min="1" name="guestCount" value={inquiry.guestCount} onChange={onChange} />
                </label>
                <label>
                  Budget
                  <input name="budget" value={inquiry.budget} onChange={onChange} placeholder="Example: 5 lakh" />
                </label>
                <label>
                  Location
                  <input name="location" value={inquiry.location} onChange={onChange} />
                </label>
              </div>
              <label>
                Description / Requirements
                <textarea name="message" value={inquiry.message} onChange={onChange} rows="4" required />
              </label>
              {status.message && <p className={`form-message ${status.type}`}>{status.message}</p>}
              <button className="button primary full" type="submit" disabled={loading}>
                <Send size={18} />
                {loading ? "Sending..." : "Send Request to Contact us"}
              </button>
            </form>
          </section>
        </div>
      )}
    </main>
  );
};

export default Home;
